// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/14/2024, 6:59:16 PM
const configMerger = require("/Users/georges-antoine/workspace/marketing-site/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/georges-antoine/workspace/marketing-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/plugins/**/*.{js,ts,mjs}","/Users/georges-antoine/workspace/marketing-site/composables/**/*.{js,ts,mjs}","/Users/georges-antoine/workspace/marketing-site/utils/**/*.{js,ts,mjs}","/Users/georges-antoine/workspace/marketing-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/georges-antoine/workspace/marketing-site/app.config.{js,ts,mjs}"] }));

module.exports = config
